package pojo;
// Generated 06-feb-2017 10:41:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private Integer idbill;
     private String idper;
     private String date;
     private String observations;

    public Bill() {
    }

	
    public Bill(String idper, String date) {
        this.idper = idper;
        this.date = date;
    }
    public Bill(String idper, String date, String observations) {
       this.idper = idper;
       this.date = date;
       this.observations = observations;
    }
   
    public Integer getIdbill() {
        return this.idbill;
    }
    
    public void setIdbill(Integer idbill) {
        this.idbill = idbill;
    }
    public String getIdper() {
        return this.idper;
    }
    
    public void setIdper(String idper) {
        this.idper = idper;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getObservations() {
        return this.observations;
    }
    
    public void setObservations(String observations) {
        this.observations = observations;
    }




}


