package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1

/**
 * BillLines generated by hbm2java
 */
public class BillLines implements java.io.Serializable {

    private int id;
    private int idbill;
    private int idpet;
    private int quantity;
    private int taxes;
    private int discount;
    private double price;
    private String namepet;
    private String observations;
    private String nameprod;
    private int idprod;

    public BillLines() {
    }

    public BillLines(int id, int bill, Products prod) {
        this.id = id;
        this.idbill = bill;
    }

    public BillLines(int idpet, String namepet, int idprod, String nameprod, int quantity, double price, int taxes, int discount) {
        this.id = 0;
        this.idbill = 0;
        this.idpet = idpet;
        this.idprod = idprod;
        this.nameprod = nameprod;
        this.quantity = quantity;
        this.taxes = taxes;
        this.discount = discount;
        this.price = price;
        this.namepet = namepet;
        this.observations = "";

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdbill() {
        return idbill;
    }

    public void setIdbill(int idbill) {
        this.idbill = idbill;
    }

    public int getIdpet() {
        return idpet;
    }

    public void setIdpet(int idpet) {
        this.idpet = idpet;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getTaxes() {
        return taxes;
    }

    public void setTaxes(int taxes) {
        this.taxes = taxes;
    }

    public int getDiscount() {
        return discount;
    }

    public void setDiscount(int discount) {
        this.discount = discount;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getNamepet() {
        return namepet;
    }

    public void setNamepet(String namepet) {
        this.namepet = namepet;
    }

    public String getObservations() {
        return observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }

    public String getNameprod() {
        return nameprod;
    }

    public void setNameprod(String nameprod) {
        this.nameprod = nameprod;
    }

    public int getIdprod() {
        return idprod;
    }

    public void setIdprod(int idprod) {
        this.idprod = idprod;
    }

    

}
