package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Consultation generated by hbm2java
 */
public class Consultation  implements java.io.Serializable {


     private Integer idcons;
     private Pets pets;
     private int idpets;
     private String date;
     private String reason;
     private String diagnosis;
     private String treatment;
     private String observation;
     private Set docs = new HashSet(0);

    public Consultation() {
    }

	
    public Consultation(Pets pets, String date, String reason, String diagnosis) {
        this.pets = pets;
        this.date = date;
        this.reason = reason;
        this.diagnosis = diagnosis;
    }
    public Consultation(Pets pets, String date, String reason, String diagnosis, String treatment, String observation, Set docs) {
       this.pets = pets;
       this.date = date;
       this.reason = reason;
       this.diagnosis = diagnosis;
       this.treatment = treatment;
       this.observation = observation;
       this.docs = docs;
    }
   
    public Integer getIdcons() {
        return this.idcons;
    }
    
    public void setIdcons(Integer idcons) {
        this.idcons = idcons;
    }
    public Pets getPets() {
        return this.pets;
    }
    
    public void setPets(Pets pets) {
        this.pets = pets;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getDiagnosis() {
        return this.diagnosis;
    }
    
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }
    public Set getDocs() {
        return this.docs;
    }
    
    public void setDocs(Set docs) {
        this.docs = docs;
    }

    public int getIdpets() {
        return idpets;
    }

    public void setIdpets(int idpets) {
        this.idpets = idpets;
    }

    @Override
    public String toString() {
        return "Consultation{" + "idcons=" + idcons + ", pets=" + pets + ", idpets=" + idpets + ", date=" + date + ", reason=" + reason + ", diagnosis=" + diagnosis + ", treatment=" + treatment + ", observation=" + observation + ", docs=" + docs + '}';
    }

}


