package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Dates generated by hbm2java
 */
public class Dates implements java.io.Serializable {

    private int id;
    private String date;
    private String idperson;
    private Date hour;
    private String observations;
    private String nameper;
    private String namepet;
    private int type;

    public Dates() {
    }

    public Dates(int id, String person, Date hour) {
        this.id = id;
        this.idperson = person;
        this.hour = hour;
    }

    public Dates(int id, String person, Date hour, String observations, String nameper, String namepet) {
        this.id = id;
        this.idperson = person;
        this.hour = hour;
        this.observations = observations;
        this.nameper = nameper;
        this.namepet = namepet;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPerson() {
        return this.idperson;
    }

    public void setPerson(String person) {
        this.idperson = person;
    }

    public Date getHour() {
        return this.hour;
    }

    public void setHour(Date hour) {
        this.hour = hour;
    }

    public String getObservations() {
        return this.observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getNameper() {
        return nameper;
    }

    public void setNameper(String nameper) {
        this.nameper = nameper;
    }

    public String getNamepet() {
        return namepet;
    }

    public void setNamepet(String namepet) {
        this.namepet = namepet;
    }

}
