package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1

/**
 * Pets generated by hbm2java
 */
public class Pets implements java.io.Serializable {

    private int idpets;
    private Person person;
    private String namepet;
    private String animal;
    private int gender;
    private String race;
    private String colour;
    private String birthDate;

    public Pets() {
    }

    public Pets(Person person, String namepet, String animal) {
        this.person = person;
        this.namepet = namepet;
        this.animal = animal;
    }

    public Pets(Person person, String namepet, String animal, int gender, String race, String colour, String birthDate) {
        this.person = person;
        this.namepet = namepet;
        this.animal = animal;
        this.gender = gender;
        this.race = race;
        this.colour = colour;
        this.birthDate = birthDate;
    }

    public int getIdpets() {
        return this.idpets;
    }

    public void setIdpets(int idpets) {
        this.idpets = idpets;
    }

    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public String getNamepet() {
        return this.namepet;
    }

    public void setNamepet(String namepet) {
        this.namepet = namepet;
    }

    public String getAnimal() {
        return this.animal;
    }

    public void setAnimal(String animal) {
        this.animal = animal;
    }

    public int getGender() {
        return this.gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public String getRace() {
        return this.race;
    }

    public void setRace(String race) {
        this.race = race;
    }

    public String getColour() {
        return this.colour;
    }

    public void setColour(String colour) {
        this.colour = colour;
    }

    public String getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    @Override
    public String toString() {
        return idpets + "-" + namepet;
    }
}
