package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Vaccines generated by hbm2java
 */
public class Vaccines implements java.io.Serializable {

    private int idvac;
    private int idpet;
    private String date_vaccine;
    private String observaciones;
    private String name_vaccine;
    private Pets pets;

    public Vaccines() {
    }

    public Vaccines(int idvac, int idpet, String date_vaccine, String observaciones, String name_vaccine, Pets pets) {
        this.idvac = idvac;
        this.idpet = idpet;
        this.date_vaccine = date_vaccine;
        this.observaciones = observaciones;
        this.name_vaccine = name_vaccine;
        this.pets = pets;
    }

    public int getIdvac() {
        return idvac;
    }

    public void setIdvac(int idvac) {
        this.idvac = idvac;
    }

    public int getIdpet() {
        return idpet;
    }

    public void setIdpet(int idpet) {
        this.idpet = idpet;
    }

    public String getDate_vaccine() {
        return date_vaccine;
    }

    public void setDate_vaccine(String date_vaccine) {
        this.date_vaccine = date_vaccine;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getName_vaccine() {
        return name_vaccine;
    }

    public void setName_vaccine(String name_vaccine) {
        this.name_vaccine = name_vaccine;
    }

    public Pets getPets() {
        return pets;
    }

    public void setPets(Pets pets) {
        this.pets = pets;
    }

    @Override
    public String toString() {
        return name_vaccine;
    }

}
